### ISSUE TITLE
[Suggestion] Add package name in /api/v1/id/<id>

### ISSUE THREAD

**Issue by konqiDAM** [ComputerElite/OculusDB#1]
That's it, I would appreciate if you could get package names for the games.

**Comment by ComputerElite** [comment]
IIrc OculusDB doesn't keep track of that. However I'll add it

**Comment by ComputerElite** [comment]
Out of interest, what do you plan to use the api for?

**Comment by konqiDAM** [comment]
Thank you! Yeah I tried it to scrap some time ago and wasn't able to do it. But the "down quest" extension is able to retrieve it.

I wanted to scrap all games with package name to have a whitelist of games. Right now I have a problem that I cant differentiate oculus games/apps to any regular android game. I can look it up in playstore, but its not really enough for me.

**Comment by ComputerElite** [comment]
Hm I don't really get for what you want a whitelist of games. Trying to do some anti piracy stuff?

**Comment by konqiDAM** [comment]
I'm doing an app that connects from pc to quest and retrieves installed games to share save games and load them from other people. But I don't want to show games that are not from oculus.

**Comment by ComputerElite** [comment]
nice. Currently looking into how to get the package name. My all knowing request doesn't seem to have it but I remember seeing them somewhere. I'll continue to search

**Comment by ComputerElite** [comment]
Also idk if you already use it but OculusDB got api documentation https://oculusdb.rui2015.me/api/docs

**Comment by konqiDAM** [comment]
Thanks for looking into it. If you use the down quest extension it can show it 
![image](https://user-images.githubusercontent.com/44301655/167269478-481b4322-95f6-4d4b-a47d-b4231d959bfa.png)
![image](https://user-images.githubusercontent.com/44301655/167269484-c9eabe6e-57c3-4ed8-97bd-1af5d2504659.png)
![image](https://user-images.githubusercontent.com/44301655/167269486-7fdf91b2-ad0d-4150-963f-565faf8e2b19.png)
![image](https://user-images.githubusercontent.com/44301655/167269488-89727dd7-9492-4d31-98b9-909003b19deb.png)

**Comment by ComputerElite** [comment]
Oh that request, right. Thanks!

**Comment by ComputerElite** [comment]
also delete that picture, it contains your token

**Comment by ComputerElite** [comment]
And you probably want to change your password to make that token invalid

**Comment by konqiDAM** [comment]
oh, didnt know it was critical, ty

**Comment by ComputerElite** [comment]
The token gives whoever has it full access to your account

**Comment by ComputerElite** [comment]
Alright I got package names added. OculusDB will probably take a few hours until everything is updated. I'll run OculusDB on my Computer so that helps. If all goes well everything should be updated in 1 - 3 hours. I'll add api endpoints to search by package name and add searching by package name to the regular search endpoint. Thanks for your suggestion.

**Comment by ComputerElite** [comment]
Update has been deployed and the first package names should start appearing. Endpoint /api/v1/packagename has been added. commit: https://github.com/ComputerElite/OculusDB/commit/2c343f03a812ea0a7c0487f7de92ea2dd9412820

**Comment by ComputerElite** [comment]
https://oculusdb.rui2015.me/api/v1/packagename/com.vankrupt.pavlovbeta example of the api
