### ISSUE TITLE
It wont search

### ISSUE THREAD

**Issue by AJcodes90** [ComputerElite/OculusDB#3]
I've Tried searching and it wont

**Comment by AJcodes90** [comment]
Can you help me with this?

**Comment by AJcodes90** [comment]
Hello?

**Comment by AJcodes90** [comment]
HELP :/

**Comment by Pattycake123** [comment]
Yeah It won't let me search either it will just freeze

**Comment by Pattycake123** [comment]
Helllloooooo

**Comment by Pattycake123** [comment]
![chrome_screenshot_1654653609190](https://user-images.githubusercontent.com/107088038/172515119-197eb20f-3208-4dfb-a3b3-80361cbc4266.png)

**Comment by Pattycake123** [comment]
#4

**Comment by Pattycake123** [comment]
@ComputerElite can you fix this

**Comment by ComputerElite** [comment]
Pushed an update that should fix everything. You should be able to search within the next few minutes

And heck spamming won't let me wake up earlier
