### ISSUE TITLE
You can get free games if you dont log in

### ISSUE THREAD

**Issue by valentin657900** [ComputerElite/OculusDB#5]
![Screenshot_20220702-141910_Chrome](https://user-images.githubusercontent.com/78165519/177012141-c8a8d498-7535-4e6b-af08-79894dabc4fb.jpg)

![Screenshot_20220702-141927_Chrome](https://user-images.githubusercontent.com/78165519/177012169-41d17802-faea-45a3-a4f1-e9a660aa4a2b.jpg)

I dont have the game but i can download it anyways

**Comment by ComputerElite** [comment]
wow. As I'm not responsible for checking if you own the game (that's Oculus job) I can't do anything about that.
Are you able to download other games as well?

**Comment by ComputerElite** [comment]
However most games check if you own the game when being started. That check is usually reliable

**Comment by valentin657900** [comment]
> wow. As I'm not responsible for checking if you own the game (that's Oculus job) I can't do anything about that. Are you able to download other games as well?

I can download every apk

**Comment by ComputerElite** [comment]
That's bad. For now I'm closing OculusDB for everyone
