### ISSUE TITLE
Can't patch my app (Gorilla tag)

### ISSUE THREAD

**Issue by Kiwi222222** [ComputerElite/OculusDB#9]
Hi.  I am new to this whole process with patching your apps on Quest 2.  I'm trying to patch gorilla tag using questpatcher, and I get this message.  I can't seem to figure out this libunity.so issue.   Is there a step I'm missing?  I used sidequest to install the app, and that works, but this part will not work when I try to patch app using questpatcher.  I've tried installing many versions of gorilla tag and it gives me the same message
![image](https://user-images.githubusercontent.com/124395183/216686256-f78e0b9b-74d2-4ffc-bcde-6a057145d2fe.png)

**Comment by FranciscoRibeiro03** [comment]
That's an error on QuestPatcher, not OculusDB
Either way, looking at the versions database, the versions that have an unstripped unity available are:
- 1.0.2 to 1.0.11
- 1.1.0 to 1.1.27, excluding 1.1.26

**Comment by Kiwi222222** [comment]
Thank you for the response.  I tried 1.0.11 and reran the patch my app.  This is what I got back.  Not sure why it mentions beat saber?
![image](https://user-images.githubusercontent.com/124395183/216689693-f326a0ff-b0cb-4551-a908-bc08f4dabbea.png)

**Comment by FranciscoRibeiro03** [comment]
Once again, this is a QuestPatcher issue, not an OculusDB one
Open an issue on the [correct repository](https://github.com/Lauriethefish/QuestPatcher)
